packages:
  - apps/*
  - packages/*

catalog:
  '@iconify/react': ^6.0.2
  '@libsql/client': ^0.15.15
  '@cloudflare/vite-plugin': ^1.23.0
  '@orpc/client': ^1.10.4
  '@orpc/server': ^1.10.4
  '@orpc/tanstack-query': ^1.10.4
  '@t3-oss/env-core': 0.13.8
  '@tailwindcss/cli': ^4.1.18
  '@tailwindcss/postcss': ^4.1.18
  '@tailwindcss/vite': ^4.1.18
  '@tanstack/nitro-v2-vite-plugin': ^1.154.7
  '@tanstack/react-devtools': ^0.9.4
  '@tanstack/react-query': ^5.90.20
  '@tanstack/react-query-devtools': ^5.91.3
  '@tanstack/react-router': ^1.158.0
  '@tanstack/react-router-devtools': ^1.158.0
  '@tanstack/react-router-ssr-query': ^1.158.0
  '@tanstack/react-router-with-query': ^1.130.17
  '@tanstack/react-start': ^1.158.0
  '@tanstack/router-devtools': ^1.158.0
  '@tanstack/router-plugin': ^1.158.0
  '@testing-library/dom': ^10.4.1
  '@testing-library/react': ^16.3.0
  '@types/node': 22.15.29
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  '@vitejs/plugin-react': ^5.1.3
  argon2: 0.31.2
  animate.css: ^4.1.1
  autoprefixer: 10.4.21
  cheerio: ^1.2.0
  better-auth: ^1.3.34
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  dotenv: ^17.2.3
  drizzle-arktype: ^0.1.3
  drizzle-kit: ^0.31.6
  drizzle-orm: ^0.44.7
  es-toolkit: ^1.41.0
  eslint: ^9.39.1
  eslint-plugin-react-hooks: ^7.0.1
  jiti: ^2.6.1
  jsdom: ^27.1.0
  lucide-react: ^0.553.0
  motion: ^12.23.24

  postcss: ^8.5.6
  prettier: ^3.6.2
  radix-ui: ^1.4.3
  react: ^19.2.4
  react-dom: ^19.2.4
  superjson: ^2.2.5
  swd-eslint-config: 2.3.1
  tailwind-merge: ^3.3.1
  tailwindcss: 4.1.17
  turbo: ^2.6.0
  tw-animate-css: ^1.4.0
  typescript: 5.9.3
  typescript-eslint: ^8.46.3
  usehooks-ts: ^3.1.1
  vinxi: ^0.5.11
  vite: ^8.0.0-beta.12
  vitest: ^4.0.18
  web-vitals: 5.1.0
  wrangler: ^4.62.0
  zod: ^4.1.12
  '@upstash/redis': ^1.36.1
  dayjs: ^1.11.19

onlyBuiltDependencies:
  - argon2
