packages:
  - apps/*
  - packages/*

catalog:
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  '@types/node': 22.15.29
  '@tanstack/router-plugin': ^1.134.15
  '@tanstack/react-router': ^1.134.15
  '@tanstack/router-devtools': ^1.134.15
  '@tanstack/react-start': ^1.134.15
  '@tanstack/react-router-devtools': ^1.134.15
  '@tailwindcss/cli': ^4.1.17
  '@tailwindcss/postcss': ^4.1.17
  better-auth: ^1.3.34
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  tailwind-merge: ^3.3.1
  eslint: ^9.39.1
  typescript-eslint: ^8.46.3
  eslint-plugin-react-hooks: ^7.0.1
  '@vitejs/plugin-react': ^5.1.0
  autoprefixer: 10.4.21
  jiti: ^2.6.1
  postcss: ^8.5.6
  react: ^19.2.0
  react-dom: ^19.2.0
  swd-eslint-config: 2.3.1
  prettier: ^3.6.2
  radix-ui: ^1.4.3
  tailwindcss: 4.1.17
  turbo: ^2.6.0
  typescript: 5.9.3
  vite: ^7.2.2
  vite-tsconfig-paths: ^5.1.4
  '@tanstack/react-query': ^5.90.7
  '@t3-oss/env-core': 0.13.8
  '@tailwindcss/vite': ^4.1.17
  '@tanstack/react-query-devtools': ^5.90.2
  '@tanstack/react-router-with-query': ^1.130.17
  '@orpc/client': ^1.10.4
  '@orpc/server': ^1.10.4
  '@orpc/tanstack-query': ^1.10.4
  superjson: ^2.2.5
  vinxi: ^0.5.8
  zod: ^4.1.12
  '@testing-library/dom': ^10.4.1
  '@testing-library/react': ^16.3.0
  jsdom: ^27.1.0
  usehooks-ts: ^3.1.1
  vitest: ^4.0.8
  web-vitals: 5.1.0
  tw-animate-css: ^1.4.0
  '@tanstack/nitro-v2-vite-plugin': ^1.133.19
  '@tanstack/react-devtools': ^0.8.1
  '@tanstack/react-router-ssr-query': ^1.134.15
  lucide-react: ^0.553.0
  '@libsql/client': ^0.15.15
  drizzle-arktype: ^0.1.3
  drizzle-kit: ^0.31.6
  drizzle-orm: ^0.44.7
  es-toolkit: ^1.41.0
  argon2: 0.31.2
  '@iconify/react': ^6.0.2
  dotenv: ^17.2.3

onlyBuiltDependencies:
  - argon2
